### ISSUE TITLE
Creating testnet address and test coin 

### ISSUE THREAD

**Issue by dgarey** [jaelcartel/claim#12]
Current plans are to duplicate claim wallet and Discoin token amount. How many test wallets do we want for the DB?

**Comment by cherrries** [comment]
just enough to cover all edge cases should be enough for now, I think. 👍 

- unclaimed
- stuck
- already claimed
- quantity:1
- quantity: > 1 
etc.

**Comment by dgarey** [comment]
1payment.addr 2payment.addr 3payment.addr 4payment.addr 5payment.addr
addr_test1vr5v5vy74qunv5xjnnfe98nkkz46lxtmc5lqjmmg6wkvxnq6azwve
addr_test1vq3prgmqy5q8kl0lfzp827e08t8whg60sjjxgxardtrqk6gzk3ptw
addr_test1vqd47p76pp27edmrcfst66mwvhnpxwpvck46k33cz84nutgtzlg97
addr_test1vz66tknt0tn8w0uq67seye7n4q7mj0yymd2fy8ma4tz9jys8t83k4
addr_test1vq0lmrpcdyz8zjyyxx4up9c9t9wcdu27nxkmm04nswxfk8qtw7aufcd 

Amount -                                                Policy Number.AssetName 
5777000000 077a02835218ebad191eb7d593cc581f81a1cc0705484e1b48aa1e4d.54646973636f696e 

Will compile script address tomorrow.

**Comment by dgarey** [comment]
Script address has been compiled to: addr_test1wq00a68ht7k3lvs7gk7hmgajrjudrelxj34hxsrt3nsm70qmywmlm
All the tokens have been distributed into the contract and locked with the 
Datum hash- ef0b9e13883a723ab5ef8bd2e9d8512b2bf2422f1613fe7c08aade70a23b80e9
